### ISSUE TITLE
MS Translator v1 API no longer working

### ISSUE THREAD

**Issue by saucyfox** [0x263b/Porygon2#3]
I recently set up Porygon2, and I noticed that the -translate command always resulted in "Could not get translation" despite the fact that I supplied valid credentials for TranslateClient and TranslateSecret. I noticed that the translate command is using the v1 API with HTTP basic auth, so I decided to test it (both with curl and firefox) and I wasn't able to authenticate.

I checked the official documentation, and it looks like the v1 API is deprecated. Following [this](https://msdn.microsoft.com/en-us/library/hh454950.aspx) article to obtain an access token and [this](https://msdn.microsoft.com/en-us/library/ff512421.aspx) article to use the Translate method, I was able write a small script capable of doing basic translations:

``` bash
#!/bin/bash
# translate.sh
# Requires jq; a command-line json processor

client_id=$1
client_secret=$2
from=$3
to=$4
text=$5
uri='https://api.microsofttranslator.com/v2/Http.svc/Translate'

if [ $# -ne 5 ]; then
    echo 'Usage: ./translate.sh client_id client_secret from_lang to_lang "my text"'
    exit 2
fi

token=$(curl -s \
    --data-urlencode "grant_type=client_credentials" \
    --data-urlencode "client_id=$client_id" \
    --data-urlencode "client_secret=$client_secret" \
    --data-urlencode "scope=http://api.microsofttranslator.com" \
    "https://datamarket.accesscontrol.windows.net/v2/OAuth2-13" | jq ".access_token" | \
    sed -r -e 's/^"|"$//') # Strip quotes added by jq

curl -s -G -H "Authorization: Bearer $token" \
    --data-urlencode "text=$text" \
    --data-urlencode "from=$from" \
    --data-urlencode "to=$to" \
    $uri | grep '<string' | cut -f2 -d '>' | cut -f1 -d '<' # Strip XML tags
```

I'd submit a patch myself, but I don't know Go. However, I think the above script makes it pretty clear how the new API works:
- Send a POST request to https://datamarket.accesscontrol.windows.net/v2/OAuth2-13; setting `grant_type` to client_credentials, `client_id` to your client ID, `client_secret` to your client secret, and `scope` to http://api.microsofttranslator.com
- If successful, this should return a json object with the key access_token. This is what we use to authenticate. Note that it expires after 10 minutes.
- To use the API, set the `Authorization` header to `Bearer <your token here>` in your requests. Everything else should basically be the same; aside from the lack of HTTP basic auth and a different URI. It also appears that there's no way to tell the Translate method to return a json object as its response.

I hope this was helpful, and thanks for your time.

**Comment by 0x263b** [comment]
This was fixed a few months ago. Take a look at [this commit](https://github.com/0x263b/Porygon2/commit/4363c60c7548d6fd9dde7342f5263e1bf11bb9ac)

Edit ---

Go to the [Azure Marketplace](https://datamarket.azure.com/dataset/bing/microsofttranslator) and subscribe to Microsoft Translator, then test it with the [Service Explorer](https://datamarket.azure.com/dataset/explore/bing/microsofttranslator).

Top of the page, you'll see the `Primary Account Key` which will be the `TranslateSecret` (`TranslateClient`  can be left blank, but I use the bot name).

I should probably write a setup guide with all the API details at some point.

**Comment by saucyfox** [comment]
Oh, sorry about that. I was using the client secret that can be seen at `https://datamarket.azure.com/developer/applications/edit/<your_client_id>`. The naming is admittedly a bit confusing. Thanks for your help!
